---

- name: create download directory
  ansible.builtin.file:
    path: "{{ geoip_remote_tmp_directory }}"
    state: directory
    mode: "0750"
  check_mode: false

- name: download binary archive
  ansible.builtin.get_url:
    url: "{{ geoip_source_base }}/{{ item }}"
    dest: "{{ geoip_remote_tmp_directory }}/{{ item | geoip_filename() }}"
    mode: "0640"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  loop: "{{ geoip_download_files }}"
  loop_control:
    label: "file: {{ geoip_source_base }}/{{ item }}"

...
