---

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr == 'systemd'

- name: restart geoip-update
  become: true
  ansible.builtin.service:
    name: geoip-update
    state: restarted

...
