---

geoip_legacy: false

geoip_maxmind:
  account_id: "{{ vault__account_id | default('1111111') }}"
  license_key: "{{ vault__license_key | default('XXXXX_sdfmsdkfnklsdnfkjasndkjasndbfjkbasdf_yyy') }}"
  edition_ids:
    - GeoLite2-ASN
    - GeoLite2-City
    - GeoLite2-Country

# geoip_databases:
#   db_ip:
#     country:
#       both: true
#       ipv4: true
#       ipv6: false
#     city:
#       both: true
#       ipv4: false
#       ipv6: true
#   maxmind:
#     asn:
#       both: false
#       ipv4: false
#       ipv6: false
#     country:
#       both: false
#       ipv4: false
#       ipv6: false
#     city:
#       both: false
#       ipv4: false
#       ipv6: false

...
